name: Lint

on:
  - pull_request
  - push

jobs:

  lint:
    name: Rust ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ stable, "1.74" ]
    steps:

      - uses: actions/checkout@v4

      - name: Set Rust version
        run: rustup default ${{ matrix.rust }}

      - name: Install cargo-fmt and cargo-clippy
        run: rustup component add rustfmt clippy

      - name: Lint
        run: ./lint.sh

  minimal-dependency-versions:
    name: Validate minimal dependency versions
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set Rust version
        run: rustup default 1.74

      - name: Install cargo-hack and cargo-minimal-versions
        run: |
          rustup toolchain add nightly &&
          cargo +nightly install cargo-hack cargo-minimal-versions --locked

      - name: Validate minimal dependency versions
        run: cargo minimal-versions check --workspace
